version: '3.3'

services:
    db:
        image: postgis/postgis:15-3.4
        ports:
            - 15437:5432
        volumes:
            - /opt/ciimbmailw:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: awmyb
        networks:
            - backend

networks:
    backend:
        external:
            name: chiroposture_network

