version: '3'

services:
#    db:
#        restart: always
#        image: postgres
#        volumes:
#            - ../postgres-data:/var/lib/postgresql/data
#            - ../pg-backup:/home/pg-backup
#        environment:
#          POSTGRES_DB: mailapi
#
    mail-api:
        build: .
        volumes:
            - ./imap-api/mailapi:/home/web/codes
            - /opt/var/mail-api.ciimbre.com/sock:/home/sock
            - /opt/var/mail-api.ciimbre.com/mail-server-confs/postfix-accounts.cf:/postfix-accounts.cf
        ports:
            - 8999:8000
        command: /usr/local/bin/gunicorn --env DJANGO_SETTINGS_MODULE=mailapi.settings mailapi.wsgi --workers 3 --bind=unix:/home/sock/api.sock
        entrypoint: /entrypoint.sh
        restart: always
