# Generated by Django 2.1.7 on 2019-03-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Account'),
            preserve_default=False,
        ),
    ]
