# Generated by Django 2.1.7 on 2019-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mail_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_on_server',
            field=models.BooleanField(default=False),
        ),
    ]
